
INSERT INTO compositions (composition_id, energetics_id, taurine, caffeine)
VALUES 
    (1, null, 400, 32), 
    (2, null, 380, 30),
	(3,null,240,30),
	(4,null,40,30),
	(5,null,30,27),
	(6,null,400,32),
	(7,null,400,30),
	(8,null,240,32),
	(9,null,400,30),
	(10,null,50,30),
	(11,null,0,32),
	(12,null,200,50);
	

INSERT INTO energetics (name, taste, description, manufacturer_name, manufacture_country, composition_id, picture_url)
VALUES 
    ('Monster&reg', 'Pipeline Punch', 'A flavour like sakura, glowy barby-like pink metal casing and monstrous notorious but beloved Monster&reg logo on top!', 'Monster Beverage', 'USA', 1, '/static/img/cover_monster_punch_pipeline.png'),
    ('KAIF&reg', 'Mojito Virgin', 'Astonishing and refreshing! Top german bewerage with real mint on the tip of your tongue!', 'Ancor Group Germany GmbH', 'Germany', 2, '/static/img/cover_kaif_mojito.png'),
	('Lit Energy','Blueberry','Peachy soft and wet blueberries from taiga itself were magically transformed into this delicious drink!','Lit Energy','Russia',3,'/static/img/cover_lit_blueberry.png'),
	('Tornado&reg','Cactus','Have you ever tasted a CACTUS? A spiky flavor made of exotic fruits (yes, cactus is a fruit!) that will tingle you up.','Global Functional Drinks Rus Ltd.','Russia',4,'/static/img/cover_tornado_cactus.png'),
	('Gorilla','Mint','Mint tic tac in a liquid form. Don''t freeze your lips!','Gorilla Drinks Limited','Cyprus',5,'/static/img/cover_gorilla_mint.png'),
	('RedBull&reg','Red Edition','Red stands for Really ExiteD4theWATERMELONTASTE! Classical RedBull&reg quality, now flavored with your favourite summer dish!','Red Bull GmbH','Austria',6,'/static/img/cover_redbull_red.png'),
	('NonStop','Original','A classic taste straight from our beloved post-apocalyptic game! A blowout is coming, stalkers...','New Products Group','Ukraine',7,'/static/img/cover_nonstop_original.png'),
	('Carabao&reg','Green Apple','Classic Carabao&reg, now with gentle apple touch. Totally green and totally energizing.','Carabao Tawandang Co.','Thailand',8,'/static/img/cover_carabao_greenapple.png'),
	('Monster&reg','Pacific Punch','Set sail with Monster&reg and this otherworldly exotic citrus flavour with a pinch of cinnamon aroma. Reminds of navy lore...','Monster Beverage','USA',9,'/static/img/cover_monster_punch_pacific.png'),
	('Jaguar&reg','Cult','Forest berries are freshly transformed into iconic 2007 hype drink. Do not overhype, but overcharge!','United Bottling Group','Russia',10,'/static/img/cover_jaguar_cult.png'),
	('CocaCola&reg','Energy','Yes, this thing exists. Now you can throw away all other ''cola'' energy replicas and experience the real brand and original coke flavour.','The Coca-Cola Company','USA',11,'/static/img/cover_cocacola_energy.png'),
	('Firegin','Original','A heartrate killer from Korea. It''s not a Cocaine Energy, but still will punch your grumpy face up!','Firegin Co Ltd','South Korea',12,'/static/img/cover_firegin.png'), 
	('Zestful', 'Citrus', 'Energizing burst of tanginess', 'EnerGize Corp.', 'USA', 13, ''),
('Vivid', 'Berry', 'Bold and invigorating flavor explosion', 'VigorMax Inc.', 'Canada', 14, ''),
('Revitalize', 'Tropical', 'Refreshingly exotic with a revitalizing kick', 'RevivePlus Ltd.', 'Australia', 15, ''),
('PowerPunch', 'Pineapple', 'Punchy fusion of tropical sweetness', 'PowerUp Enterprises', 'UK', 16, ''),
('VigorVerve', 'Cranberry', 'Vibrant cranberry kick for a burst of verve', 'VigorVerve Wellness', 'USA', 17, ''),
('EnerJoy', 'Lemon', 'Zesty and uplifting with a hint of joy', 'EnerJoy Nutritionals', 'Canada', 18, ''),
('BuzzBlend', 'Coffee', 'Rich and robust for a caffeine buzz', 'BuzzBlend Co.', 'USA', 19, ''),
('ZingZang', 'Ginger', 'Spicy zing with a tangy twist', 'ZingZang Innovations', 'Australia', 20, ''),
('PepPepper', 'Pepper', 'Spicy and fiery to pep you up', 'PepPepper Solutions', 'UK', 21, ''),
('MegaMint', 'Mint', 'Refreshingly cool and mega rejuvenating', 'MegaMint Beverages', 'USA', 22, ''),
('ChargeCherry', 'Cherry', 'Sweet and tart charge of fruity energy', 'ChargeCherry Ltd.', 'Canada', 23, ''),
('SparkSplash', 'Watermelon', 'Bursting with refreshing spark and splash', 'SparkSplash Co.', 'Australia', 24, ''),
('KickKola', 'Cola', 'Classic cola kick with an energy boost', 'KickKola Inc.', 'UK', 25, ''),
('ZapZen', 'Green Apple', 'Crisp and zen-inducing zap of energy', 'ZapZen Wellness', 'USA', 26, ''),
('VitaliTea', 'Herbal', 'Naturally invigorating herbal infusion', 'VitaliTea Blends', 'Canada', 27, ''),
('ThrillTonic', 'Lemon', 'Tart and thrilling tonic for a zestful day', 'ThrillTonic Ltd.', 'Australia', 28, ''),
('EnerBrew', 'Cocoa', 'Rich and chocolaty brew for sustained energy', 'EnerBrew Corp.', 'USA', 29, ''),
('BuzzBerry', 'Blueberry', 'Buzzing with antioxidant-rich berry power', 'BuzzBerry Beverages', 'Canada', 30, ''),
('PowerPop', 'Peach', 'Pop of peachy energy to power through the day', 'PowerPop Co.', 'UK', 31, ''),
('ReviveRush', 'Raspberry', 'Rush of raspberry delight to revive your senses', 'ReviveRush Inc.', 'Australia', 32, ''),
('ZapZing', 'Mango', 'Zingy mango explosion for instant rejuvenation', 'ZapZing Nutrition', 'USA', 33, ''),
('EnerGlow', 'Orange', 'Glowing with citrus energy to light up your day', 'EnerGlow Drinks', 'Canada', 34, ''),
('PunchPomegranate', 'Pomegranate', 'Punchy pomegranate flavor bursting with vitality', 'PunchPomegranate Ltd.', 'Australia', 35, ''),
('MintyMango', 'Mango', 'Minty mango fusion for a refreshing boost', 'MintyMango Corp.', 'USA', 36, ''),
('ZestZen', 'Lime', 'Zesty lime essence infused with zen vibes', 'ZestZen Beverages', 'Canada', 37, ''),
('EnerFresh', 'Grapefruit', 'Fresh and tangy grapefruit zest to revitalize', 'EnerFresh Co.', 'UK', 38, ''),
('PowerPear', 'Pear', 'Powerful pear punch to energize your day', 'PowerPear Nutrition', 'USA', 39, ''),
('Zingology', 'Kiwi', 'Zingy kiwi delight packed with energizing nutrition', 'Zingology Inc.', 'Canada', 40, ''),
('EnerChill', 'Cucumber', 'Chill with a burst of cool cucumber energy', 'EnerChill Wellness', 'Australia', 41, ''),
('ZenZenith', 'Vanilla', 'Zenith of zen with a touch of vanilla', 'ZenZenith Wellness', 'UK', 43, ''),
('BerryBliss', 'Blackberry', 'Blissful burst of blackberry sensation', 'BerryBliss Ltd.', 'Canada', 44, ''),
('ChillCherry', 'Cherry', 'Chill cherry sensation to relax your mind', 'ChillCherry Solutions', 'USA', 45, ''),
('TropicalTingle', 'Mango', 'Tropical tingle of mango magic', 'TropicalTingle Beverages', 'Australia', 46, ''),
('CrispCranberry', 'Cranberry', 'Crisp cranberry goodness for a refreshing experience', 'CrispCranberry Inc.', 'UK', 47, ''),
('FrostFusion', 'Blue Raspberry', 'Frosty fusion of blue raspberry delight', 'FrostFusion Drinks', 'Canada', 48, ''),
('GlowGrape', 'Grape', 'Glowing grape sensation for a radiant day', 'GlowGrape Beverages', 'USA', 49, ''),
('ZestyZen', 'Lemon', 'Zesty lemon twist infused with zen vibes', 'ZestyZen Wellness', 'Australia', 50, ''),
('Elevate', 'Cucumber Mint', 'Elevate your senses with cool cucumber and mint', 'Elevate Drinks', 'UK', 51, ''),
('SparklingCitrus', 'Lime', 'Sparkling citrus burst to awaken your spirit', 'SparklingCitrus Inc.', 'Canada', 52, ''),
('SunnyCitrus', 'Orange', 'Sunny citrus sensation to brighten your day', 'SunnyCitrus Beverages', 'USA', 53, ''),
('ZapZest', 'Apple', 'Zap of apple zest for instant refreshment', 'ZapZest Nutrition', 'Australia', 54, ''),
('VibrantVibes', 'Tropical Punch', 'Vibrant vibes of tropical punch excitement', 'VibrantVibes Drinks', 'UK', 55, ''),
('BurstingBerry', 'Mixed Berry', 'Bursting berry blend for a flavorful experience', 'BurstingBerry Ltd.', 'Canada', 56, ''),
('ChillCoco', 'Coconut', 'Chill with the tropical essence of coconut', 'ChillCoco Beverages', 'USA', 57, ''),
('ZingyZest', 'Grapefruit', 'Zingy zest of grapefruit for a refreshing kick', 'ZingyZest Drinks', 'Australia', 58, ''),
('TangyTropical', 'Pineapple', 'Tangy tropical twist of pineapple delight', 'TangyTropical Beverages', 'UK', 59, ''),
('SizzleSnap', 'Ginger', 'Sizzling snap of ginger for an energizing kick', 'SizzleSnap Solutions', 'Canada', 60, ''),
('ZestfulZing', 'Lime', 'Zestful lime zing for a burst of energy', 'ZestfulZing Co.', 'USA', 61, ''),
('FruitFusion', 'Mixed Fruit', 'Fruit fusion explosion for a burst of flavor', 'FruitFusion Beverages', 'Australia', 62, ''),
('MintyMelon', 'Melon', 'Minty melon freshness for a rejuvenating experience', 'MintyMelon Ltd.', 'UK', 63, ''),
('CoolCrisp', 'Cucumber', 'Cool and crisp cucumber sensation to refresh your day', 'CoolCrisp Beverages', 'Canada', 64, ''),
('TangyTwist', 'Tangerine', 'Tangy twist of tangerine for a refreshing boost', 'TangyTwist Drinks', 'USA', 65, ''),
('ZapZap', 'Orange', 'Zap of orange energy to invigorate your senses', 'ZapZap Nutrition', 'Australia', 66, ''),
('BerryBlast', 'Mixed Berry', 'Berry blast sensation for a burst of energy', 'BerryBlast Inc.', 'UK', 67, ''),
('CherryChill', 'Cherry', 'Cherry chill to soothe your senses', 'CherryChill Beverages', 'Canada', 68, ''),
('MangoMagic', 'Mango', 'Magic of mango for a tropical sensation', 'MangoMagic Ltd.', 'USA', 69, ''),
('GingerSnap', 'Ginger', 'Snap of ginger for a zesty kick', 'GingerSnap Solutions', 'Australia', 70, ''),
('CitrusSplash', 'Citrus', 'Refreshing splash of citrus to awaken your spirit', 'CitrusSplash Beverages', 'UK', 71, ''),
('FizzyFun', 'Lemon Lime', 'Fizzing fun of lemon-lime goodness', 'FizzyFun Drinks', 'Canada', 72, ''),
('ZestyZap', 'Lemon', 'Zesty lemon zap for a refreshing burst', 'ZestyZap Beverages', 'USA', 73, ''),
('ZenBerry', 'Acai', 'Zen-like sensation with the power of acai', 'ZenBerry Wellness', 'Australia', 74, ''),
('TropicalTreat', 'Passionfruit', 'Tropical treat of passionfruit delight', 'TropicalTreat Beverages', 'UK', 75, ''),
('ChillCrisp', 'Cucumber', 'Chill with a burst of cool cucumber energy', 'ChillCrisp Wellness', 'Canada', 76, ''),
('ZenZest', 'Lime', 'Zen-like zest of lime for a refreshing experience', 'ZenZest Beverages', 'USA', 77, ''),
('TropicalTwist', 'Guava', 'Tropical twist of guava for a delightful sensation', 'TropicalTwist Drinks', 'Australia', 78, ''),
('ReviveRush', 'Kiwi', 'Rush of kiwi delight to revive your senses', 'ReviveRush Inc.', 'UK', 79, ''),
('EnerGize', 'Dragonfruit', 'Energetic burst of dragonfruit for vitality', 'EnerGize Beverages', 'Canada', 80, ''),
('MintyMist', 'Spearmint', 'Minty mist of spearmint for a refreshing boost', 'MintyMist Ltd.', 'USA', 81, ''),
('CitrusSplash', 'Grapefruit', 'Citrus splash of grapefruit to awaken your senses', 'CitrusSplash Co.', 'Australia', 82, ''),
('BerryBlast', 'Raspberry', 'Berry blast of raspberry excitement', 'BerryBlast Beverages', 'UK', 83, ''),
('CoolCrisp', 'Melon', 'Cool and crisp melon sensation for a rejuvenating experience', 'CoolCrisp Solutions', 'Canada', 84, ''),
('TangyTingle', 'Tangerine', 'Tangy tingle of tangerine for an invigorating boost', 'TangyTingle Drinks', 'USA', 85, ''),
('SparklingCitrus', 'Lemon', 'Sparkling citrus burst to brighten your day', 'SparklingCitrus Inc.', 'Australia', 86, ''),
('FrostFusion', 'Blueberry', 'Frosty fusion of blueberry delight', 'FrostFusion Ltd.', 'UK', 87, ''),
('GlowGrape', 'Concord Grape', 'Glowing grape sensation for a radiant day', 'GlowGrape Beverages', 'Canada', 88, ''),
('ZestyZen', 'Lime', 'Zesty lime twist infused with zen vibes', 'ZestyZen Drinks', 'USA', 89, ''),
('Elevate', 'Green Tea', 'Elevate your senses with the power of green tea', 'Elevate Beverages', 'Australia', 90, ''),
('FizzyFruit', 'Pineapple', 'Fizzing with fruity freshness and vigor', 'FizzyFruit Inc.', 'UK', 91, ''),
('ZenZenith', 'Jasmine', 'Zenith of zen with the essence of jasmine', 'ZenZenith Solutions', 'Canada', 92, ''),
('BurstingBerry', 'Blackcurrant', 'Bursting berry blend with blackcurrant sensation', 'BurstingBerry Drinks', 'USA', 93, ''),
('ChillCherry', 'Cherry', 'Chill cherry sensation to soothe your senses', 'ChillCherry Beverages', 'Australia', 94, ''),
('SizzleSnap', 'Chili', 'Sizzling snap of chili-infused energy', 'SizzleSnap Ltd.', 'UK', 95, ''),
('ZapZest', 'Orange', 'Zap of orange zest for an energizing burst', 'ZapZest Beverages', 'Canada', 96, ''),
('VibrantVibes', 'Tropical', 'Vibrant vibes of tropical goodness', 'VibrantVibes Inc.', 'USA', 97, ''),
('MintyMelon', 'Watermelon', 'Minty melon freshness for a rejuvenating experience', 'MintyMelon Beverages', 'Australia', 98, ''),
('SunnySplash', 'Mandarin', 'Sunny splash of mandarin for a refreshing burst', 'SunnySplash Drinks', 'UK', 99, ''),
('ZingyZing', 'Ginger', 'Zingy ginger kick for an energizing boost', 'ZingyZing Beverages', 'Canada', 100, ''),
('FrostyFusion', 'Mango', 'Frosty fusion of mango delight', 'FrostyFusion Solutions', 'USA', 101, ''),
('GlowGrape', 'Red Grape', 'Glowing red grape sensation for a radiant day', 'GlowGrape Beverages', 'Australia', 102, ''),
('ZestyZen', 'Lime', 'Zesty lime twist infused with zen vibes', 'ZestyZen Drinks', 'UK', 103, ''),
('Elevate', 'Matcha', 'Elevate your senses with the power of matcha', 'Elevate Beverages', 'Canada', 104, ''),

UPDATE compositions
SET energetics_id = (
    SELECT energetics_id
    FROM energetics
    WHERE energetics.composition_id = compositions.composition_id
);

select * from energetics
	

	
