INSERT INTO compositions (composition_id, energetics_id, taurine, caffeine)
VALUES 
    (13, null, 300, 25), 
    (14, null, 320, 35),
    (15, null, 280, 20),
    (16, null, 200, 18),
    (17, null, 400, 40),
    (18, null, 350, 28),
    (19, null, 240, 32),
    (20, null, 400, 30),
    (21, null, 50, 30),
    (22, null, 80, 10),
    (23, null, 0, 0),
    (24, null, 200, 50),
    (25, null, 300, 25), 
    (26, null, 320, 35),
    (27, null, 280, 20),
    (28, null, 200, 18),
    (29, null, 400, 40),
    (30, null, 350, 28),
    (31, null, 240, 32),
    (32, null, 400, 30),
    (33, null, 50, 30),
    (34, null, 80, 10),
    (35, null, 0, 0),
    (36, null, 200, 50),
    (37, null, 300, 25), 
    (38, null, 320, 35),
    (39, null, 280, 20),
    (40, null, 200, 18),
    (41, null, 400, 40),
    (42, null, 350, 28),
    (43, null, 240, 32),
    (44, null, 400, 30),
    (45, null, 50, 30),
    (46, null, 80, 10),
    (47, null, 0, 0),
    (48, null, 200, 50),
    (49, null, 300, 25), 
    (50, null, 320, 35),
    (51, null, 280, 20),
    (52, null, 200, 18),
    (53, null, 400, 40),
    (54, null, 350, 28),
    (55, null, 240, 32),
    (56, null, 400, 30),
    (57, null, 50, 30),
    (58, null, 80, 10),
    (59, null, 0, 0),
    (60, null, 200, 50),
    (61, null, 300, 25), 
    (62, null, 320, 35),
    (63, null, 280, 20),
    (64, null, 200, 18),
    (65, null, 400, 40),
    (66, null, 350, 28),
    (67, null, 240, 32),
    (68, null, 400, 30),
    (69, null, 50, 30),
    (70, null, 80, 10),
    (71, null, 0, 0),
    (72, null, 200, 50),
    (73, null, 300, 25), 
    (74, null, 320, 35),
    (75, null, 280, 20),
    (76, null, 200, 18),
    (77, null, 400, 40),
    (78, null, 350, 28),
    (79, null, 240, 32),
    (80, null, 400, 30),
    (81, null, 50, 30),
    (82, null, 80, 10),
    (83, null, 0, 0),
    (84, null, 200, 50),
    (85, null, 300, 25), 
    (86, null, 320, 35),
    (87, null, 280, 20),
    (88, null, 200, 18),
    (89, null, 400, 40),
    (90, null, 350, 28), 
    (91, null, 240, 32), 
    (92, null, 400, 30),
    (93, null, 50, 30),
    (94, null, 80, 10),
    (95, null, 0, 0),
    (96, null, 200, 50),
    (97, null, 300, 25), 
    (98, null, 320, 35),
    (99, null, 280, 20),
    (100, null, 200, 18),
    (101, null, 400, 40),
    (102, null, 350, 28),
    (103, null, 240, 32),
    (104, null, 400, 30);


INSERT INTO energetics (name, taste, description, manufacturer_name, manufacture_country, composition_id, picture_url)
VALUES  
	('Zestful', 'Citrus', 'Energizing burst of tanginess', 'EnerGize Corp.', 'USA', 13, '/static/img/example.png'),
('Vivid', 'Berry', 'Bold and invigorating flavor explosion', 'VigorMax Inc.', 'Canada', 14, '/static/img/example.png'),
('Revitalize', 'Tropical', 'Refreshingly exotic with a revitalizing kick', 'RevivePlus Ltd.', 'Australia', 15, '/static/img/example.png'),
('PowerPunch', 'Pineapple', 'Punchy fusion of tropical sweetness', 'PowerUp Enterprises', 'UK', 16, '/static/img/example.png'),
('VigorVerve', 'Cranberry', 'Vibrant cranberry kick for a burst of verve', 'VigorVerve Wellness', 'USA', 17, '/static/img/example.png'),
('EnerJoy', 'Lemon', 'Zesty and uplifting with a hint of joy', 'EnerJoy Nutritionals', 'Canada', 18, '/static/img/example.png'),
('BuzzBlend', 'Coffee', 'Rich and robust for a caffeine buzz', 'BuzzBlend Co.', 'USA', 19, '/static/img/example.png'),
('ZingZang', 'Ginger', 'Spicy zing with a tangy twist', 'ZingZang Innovations', 'Australia', 20, '/static/img/example.png'),
('PepPepper', 'Pepper', 'Spicy and fiery to pep you up', 'PepPepper Solutions', 'UK', 21, '/static/img/example.png'),
('MegaMint', 'Mint', 'Refreshingly cool and mega rejuvenating', 'MegaMint Beverages', 'USA', 22, '/static/img/example.png'),
('ChargeCherry', 'Cherry', 'Sweet and tart charge of fruity energy', 'ChargeCherry Ltd.', 'Canada', 23, '/static/img/example.png'),
('SparkSplash', 'Watermelon', 'Bursting with refreshing spark and splash', 'SparkSplash Co.', 'Australia', 24, '/static/img/example.png'),
('KickKola', 'Cola', 'Classic cola kick with an energy boost', 'KickKola Inc.', 'UK', 25, '/static/img/example.png'),
('ZapZen', 'Green Apple', 'Crisp and zen-inducing zap of energy', 'ZapZen Wellness', 'USA', 26, '/static/img/example.png'),
('VitaliTea', 'Herbal', 'Naturally invigorating herbal infusion', 'VitaliTea Blends', 'Canada', 27, '/static/img/example.png'),
('ThrillTonic', 'Lemon', 'Tart and thrilling tonic for a zestful day', 'ThrillTonic Ltd.', 'Australia', 28, '/static/img/example.png'),
('EnerBrew', 'Cocoa', 'Rich and chocolaty brew for sustained energy', 'EnerBrew Corp.', 'USA', 29, '/static/img/example.png'),
('BuzzBerry', 'Blueberry', 'Buzzing with antioxidant-rich berry power', 'BuzzBerry Beverages', 'Canada', 30, '/static/img/example.png'),
('PowerPop', 'Peach', 'Pop of peachy energy to power through the day', 'PowerPop Co.', 'UK', 31, '/static/img/example.png'),
('ReviveRush', 'Raspberry', 'Rush of raspberry delight to revive your senses', 'ReviveRush Inc.', 'Australia', 32, '/static/img/example.png'),
('ZapZing', 'Mango', 'Zingy mango explosion for instant rejuvenation', 'ZapZing Nutrition', 'USA', 33, '/static/img/example.png'),
('EnerGlow', 'Orange', 'Glowing with citrus energy to light up your day', 'EnerGlow Drinks', 'Canada', 34, '/static/img/example.png'),
('PunchPomegranate', 'Pomegranate', 'Punchy pomegranate flavor bursting with vitality', 'PunchPomegranate Ltd.', 'Australia', 35, '/static/img/example.png'),
('MintyMango', 'Mango', 'Minty mango fusion for a refreshing boost', 'MintyMango Corp.', 'USA', 36, '/static/img/example.png'),
('ZestZen', 'Lime', 'Zesty lime essence infused with zen vibes', 'ZestZen Beverages', 'Canada', 37, '/static/img/example.png'),
('EnerFresh', 'Grapefruit', 'Fresh and tangy grapefruit zest to revitalize', 'EnerFresh Co.', 'UK', 38, '/static/img/example.png'),
('PowerPear', 'Pear', 'Powerful pear punch to energize your day', 'PowerPear Nutrition', 'USA', 39, '/static/img/example.png'),
('Zingology', 'Kiwi', 'Zingy kiwi delight packed with energizing nutrition', 'Zingology Inc.', 'Canada', 40, '/static/img/example.png'),
('EnerChill', 'Cucumber', 'Chill with a burst of cool cucumber energy', 'EnerChill Wellness', 'Australia', 41, '/static/img/example.png'),
('ZenZenith', 'Vanilla', 'Zenith of zen with a touch of vanilla', 'ZenZenith Wellness', 'UK', 43, '/static/img/example.png'),
('BerryBliss', 'Blackberry', 'Blissful burst of blackberry sensation', 'BerryBliss Ltd.', 'Canada', 44, '/static/img/example.png'),
('ChillCherry', 'Cherry', 'Chill cherry sensation to relax your mind', 'ChillCherry Solutions', 'USA', 45, '/static/img/example.png'),
('TropicalTingle', 'Mango', 'Tropical tingle of mango magic', 'TropicalTingle Beverages', 'Australia', 46, '/static/img/example.png'),
('CrispCranberry', 'Cranberry', 'Crisp cranberry goodness for a refreshing experience', 'CrispCranberry Inc.', 'UK', 47, '/static/img/example.png'),
('FrostFusion', 'Blue Raspberry', 'Frosty fusion of blue raspberry delight', 'FrostFusion Drinks', 'Canada', 48, '/static/img/example.png'),
('GlowGrape', 'Grape', 'Glowing grape sensation for a radiant day', 'GlowGrape Beverages', 'USA', 49, '/static/img/example.png'),
('ZestyZen', 'Lemon', 'Zesty lemon twist infused with zen vibes', 'ZestyZen Wellness', 'Australia', 50, '/static/img/example.png'),
('Elevate', 'Cucumber Mint', 'Elevate your senses with cool cucumber and mint', 'Elevate Drinks', 'UK', 51, '/static/img/example.png'),
('SparklingCitrus', 'Lime', 'Sparkling citrus burst to awaken your spirit', 'SparklingCitrus Inc.', 'Canada', 52, '/static/img/example.png'),
('SunnyCitrus', 'Orange', 'Sunny citrus sensation to brighten your day', 'SunnyCitrus Beverages', 'USA', 53, '/static/img/example.png'),
('ZapZest', 'Apple', 'Zap of apple zest for instant refreshment', 'ZapZest Nutrition', 'Australia', 54, '/static/img/example.png'),
('VibrantVibes', 'Tropical Punch', 'Vibrant vibes of tropical punch excitement', 'VibrantVibes Drinks', 'UK', 55, '/static/img/example.png'),
('BurstingBerry', 'Mixed Berry', 'Bursting berry blend for a flavorful experience', 'BurstingBerry Ltd.', 'Canada', 56, '/static/img/example.png'),
('ChillCoco', 'Coconut', 'Chill with the tropical essence of coconut', 'ChillCoco Beverages', 'USA', 57, '/static/img/example.png'),
('ZingyZest', 'Grapefruit', 'Zingy zest of grapefruit for a refreshing kick', 'ZingyZest Drinks', 'Australia', 58, '/static/img/example.png'),
('TangyTropical', 'Pineapple', 'Tangy tropical twist of pineapple delight', 'TangyTropical Beverages', 'UK', 59, '/static/img/example.png'),
('SizzleSnap', 'Ginger', 'Sizzling snap of ginger for an energizing kick', 'SizzleSnap Solutions', 'Canada', 60, '/static/img/example.png'),
('ZestfulZing', 'Lime', 'Zestful lime zing for a burst of energy', 'ZestfulZing Co.', 'USA', 61, '/static/img/example.png'),
('FruitFusion', 'Mixed Fruit', 'Fruit fusion explosion for a burst of flavor', 'FruitFusion Beverages', 'Australia', 62, '/static/img/example.png'),
('MintyMelon', 'Melon', 'Minty melon freshness for a rejuvenating experience', 'MintyMelon Ltd.', 'UK', 63, '/static/img/example.png'),
('CoolCrisp', 'Cucumber', 'Cool and crisp cucumber sensation to refresh your day', 'CoolCrisp Beverages', 'Canada', 64, '/static/img/example.png'),
('TangyTwist', 'Tangerine', 'Tangy twist of tangerine for a refreshing boost', 'TangyTwist Drinks', 'USA', 65, '/static/img/example.png'),
('ZapZap', 'Orange', 'Zap of orange energy to invigorate your senses', 'ZapZap Nutrition', 'Australia', 66, '/static/img/example.png'),
('BerryBlast', 'Mixed Berry', 'Berry blast sensation for a burst of energy', 'BerryBlast Inc.', 'UK', 67, '/static/img/example.png'),
('CherryChill', 'Cherry', 'Cherry chill to soothe your senses', 'CherryChill Beverages', 'Canada', 68, '/static/img/example.png'),
('MangoMagic', 'Mango', 'Magic of mango for a tropical sensation', 'MangoMagic Ltd.', 'USA', 69, '/static/img/example.png'),
('GingerSnap', 'Ginger', 'Snap of ginger for a zesty kick', 'GingerSnap Solutions', 'Australia', 70, '/static/img/example.png'),
('CitrusSplash', 'Citrus', 'Refreshing splash of citrus to awaken your spirit', 'CitrusSplash Beverages', 'UK', 71, '/static/img/example.png'),
('FizzyFun', 'Lemon Lime', 'Fizzing fun of lemon-lime goodness', 'FizzyFun Drinks', 'Canada', 72, '/static/img/example.png'),
('ZestyZap', 'Lemon', 'Zesty lemon zap for a refreshing burst', 'ZestyZap Beverages', 'USA', 73, '/static/img/example.png'),
('ZenBerry', 'Acai', 'Zen-like sensation with the power of acai', 'ZenBerry Wellness', 'Australia', 74, '/static/img/example.png'),
('TropicalTreat', 'Passionfruit', 'Tropical treat of passionfruit delight', 'TropicalTreat Beverages', 'UK', 75, '/static/img/example.png'),
('ChillCrisp', 'Cucumber', 'Chill with a burst of cool cucumber energy', 'ChillCrisp Wellness', 'Canada', 76, '/static/img/example.png'),
('ZenZest', 'Lime', 'Zen-like zest of lime for a refreshing experience', 'ZenZest Beverages', 'USA', 77, '/static/img/example.png'),
('TropicalTwist', 'Guava', 'Tropical twist of guava for a delightful sensation', 'TropicalTwist Drinks', 'Australia', 78, '/static/img/example.png'),
('ReviveRush', 'Kiwi', 'Rush of kiwi delight to revive your senses', 'ReviveRush Inc.', 'UK', 79, '/static/img/example.png'),
('EnerGize', 'Dragonfruit', 'Energetic burst of dragonfruit for vitality', 'EnerGize Beverages', 'Canada', 80, '/static/img/example.png'),
('MintyMist', 'Spearmint', 'Minty mist of spearmint for a refreshing boost', 'MintyMist Ltd.', 'USA', 81, '/static/img/example.png'),
('CitrusSplash', 'Grapefruit', 'Citrus splash of grapefruit to awaken your senses', 'CitrusSplash Co.', 'Australia', 82, '/static/img/example.png'),
('BerryBlast', 'Raspberry', 'Berry blast of raspberry excitement', 'BerryBlast Beverages', 'UK', 83, '/static/img/example.png'),
('CoolCrisp', 'Melon', 'Cool and crisp melon sensation for a rejuvenating experience', 'CoolCrisp Solutions', 'Canada', 84, '/static/img/example.png'),
('TangyTingle', 'Tangerine', 'Tangy tingle of tangerine for an invigorating boost', 'TangyTingle Drinks', 'USA', 85, '/static/img/example.png'),
('SparklingCitrus', 'Lemon', 'Sparkling citrus burst to brighten your day', 'SparklingCitrus Inc.', 'Australia', 86, '/static/img/example.png'),
('FrostFusion', 'Blueberry', 'Frosty fusion of blueberry delight', 'FrostFusion Ltd.', 'UK', 87, '/static/img/example.png'),
('GlowGrape', 'Concord Grape', 'Glowing grape sensation for a radiant day', 'GlowGrape Beverages', 'Canada', 88, '/static/img/example.png'),
('ZestyZen', 'Lime', 'Zesty lime twist infused with zen vibes', 'ZestyZen Drinks', 'USA', 89, '/static/img/example.png'),
('Elevate', 'Green Tea', 'Elevate your senses with the power of green tea', 'Elevate Beverages', 'Australia', 90, '/static/img/example.png'),
('FizzyFruit', 'Pineapple', 'Fizzing with fruity freshness and vigor', 'FizzyFruit Inc.', 'UK', 91, '/static/img/example.png'),
('ZenZenith', 'Jasmine', 'Zenith of zen with the essence of jasmine', 'ZenZenith Solutions', 'Canada', 92, '/static/img/example.png'),
('BurstingBerry', 'Blackcurrant', 'Bursting berry blend with blackcurrant sensation', 'BurstingBerry Drinks', 'USA', 93, '/static/img/example.png'),
('ChillCherry', 'Cherry', 'Chill cherry sensation to soothe your senses', 'ChillCherry Beverages', 'Australia', 94, '/static/img/example.png'),
('SizzleSnap', 'Chili', 'Sizzling snap of chili-infused energy', 'SizzleSnap Ltd.', 'UK', 95, '/static/img/example.png'),
('ZapZest', 'Orange', 'Zap of orange zest for an energizing burst', 'ZapZest Beverages', 'Canada', 96, '/static/img/example.png'),
('VibrantVibes', 'Tropical', 'Vibrant vibes of tropical goodness', 'VibrantVibes Inc.', 'USA', 97, '/static/img/example.png'),
('MintyMelon', 'Watermelon', 'Minty melon freshness for a rejuvenating experience', 'MintyMelon Beverages', 'Australia', 98, '/static/img/example.png'),
('SunnySplash', 'Mandarin', 'Sunny splash of mandarin for a refreshing burst', 'SunnySplash Drinks', 'UK', 99, '/static/img/example.png'),
('ZingyZing', 'Ginger', 'Zingy ginger kick for an energizing boost', 'ZingyZing Beverages', 'Canada', 100, '/static/img/example.png'),
('FrostyFusion', 'Mango', 'Frosty fusion of mango delight', 'FrostyFusion Solutions', 'USA', 101, '/static/img/example.png'),
('GlowGrape', 'Red Grape', 'Glowing red grape sensation for a radiant day', 'GlowGrape Beverages', 'Australia', 102, '/static/img/example.png'),
('ZestyZen', 'Lime', 'Zesty lime twist infused with zen vibes', 'ZestyZen Drinks', 'UK', 103, '/static/img/example.png'),
('Elevate', 'Matcha', 'Elevate your senses with the power of matcha', 'Elevate Beverages', 'Canada', 104, '/static/img/example.png');

UPDATE compositions
SET energetics_id = (
    SELECT energetics_id
    FROM energetics
    WHERE energetics.composition_id = compositions.composition_id
);

select * from energetics
	